version: '3.5'
services:
    backend:
        image: backend
        build: ./backend
        volumes:
            - ./backend:/backend
        ports:
            - ${BACKEND_PORT}:3000
        expose:
            - ${BACKEND_PORT}
        env_file:
            - .env
        networks:
            - internal

    frontend:
        image: frontend
        build: ./frontend
        volumes:
            - ./frontend:/frontend
        ports:
            - ${FRONTEND_PORT}:5000
        expose:
            - ${FRONTEND_PORT}
        env_file:
            - .env
        networks:
            - internal

networks:
    internal:
        external:
            name: ${DOCKER_NETWORK}